services:
  t3static:
    build:
      context: .
      dockerfile: Dockerfile
    image: t3static:1.0.0
    container_name: t3static
    volumes:
      - ${PWD}/${TEST_PATH}:/app/${TEST_PATH}
      - ${PWD}/${PACKAGE_PATH}:/app/${PACKAGE_PATH}
      - ${PWD}/vendor:/app/vendor
