#!/bin/bash

# Check for .env file existence, if not make a copy from .env.dist
if [ ! -f t3static/.env ]; then
  cp t3static/.env.dist t3static/.env
  echo 'not .env found. copy .env.dist to .env'
fi

# Run docker-compose
docker compose -f t3static/docker-compose.yml run --rm t3static ./t3static/t3static "$@"
