#!/bin/bash

# Check for .env file existence, if not make a copy from .env.dist
if [ ! -f "${BASH_SOURCE%/*}"/.env ]; then
  cp "${BASH_SOURCE%/*}"/.env.dist "${BASH_SOURCE%/*}"/.env
  echo 'custom .env not found. copy .env.dist to .env'
fi

# Run docker-compose
docker compose -f "${BASH_SOURCE%/*}"/docker-compose.yml run --rm t3static ./t3static/t3static "$@"
