#
# .markdownlint-cli2.yaml file
#

# Define glob expressions to ignore
ignores:
  - "**/node_modules/**"
  - "**/vendor/**"

# Disable inline config comments
noInlineConfig: true

# Disable progress on stdout (only valid at root)
noProgress: true

# Show found files on stdout (only valid at root)
showFound: true
