#!/bin/bash

## Description: Run t3static inside its own container
## Usage: t3static [flags] [args]
## Example: "ddev t3static -p news_extended -t php-cs"

docker compose -f t3static/compose.yml run --rm t3static ./t3static/t3static.sh "$@"
#./t3static/t3static.sh "$@"
